# Site settings
title: Contactable
description: > # this means to ignore newlines until "baseurl:"
  Enhance Laravel users with relations to multiple e-mail addresses
  and phone numbers, additionally allowing users to login with
  any of the above.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://contactable.gridprinciples.com" # the base hostname & protocol for your site
project_url: "http://github.com/gridprinciples/contactable"
github_username:  gridprinciples

# Build settings
markdown: kramdown
highlighter: pygments
